namespace Slack\GraphQL\Introspection;

use Slack\GraphQL;

<<GraphQL\EnumType('__TypeKind', '__TypeKind')>>
enum __TypeKind: string {
    SCALAR = 'SCALAR';
    OBJECT = 'OBJECT';
    INTERFACE = 'INTERFACE';
    UNION = 'UNION';
    ENUM = 'ENUM';
    INPUT_OBJECT = 'INPUT_OBJECT';
    LIST = 'LIST';
    NON_NULL = 'NON_NULL';
}

<<GraphQL\EnumType('__DirectiveLocation', '')>>
enum __DirectiveLocation: string {
    QUERY = 'QUERY';
    MUTATION = 'MUTATION';
    SUBSCRIPTION = 'SUBSCRIPTION';
    FIELD = 'FIELD';
    FRAGMENT_DEFINITION = 'FRAGMENT_DEFINITION';
    FRAGMENT_SPREAD = 'FRAGMENT_SPREAD';
    INLINE_FRAGMENT = 'INLINE_FRAGMENT';
    VARIABLE_DEFINITION = 'VARIABLE_DEFINITION';
    SCHEMA = 'SCHEMA';
    SCALAR = 'SCALAR';
    OBJECT = 'OBJECT';
    FIELD_DEFINITION = 'FIELD_DEFINITION';
    ARGUMENT_DEFINITION = 'ARGUMENT_DEFINITION';
    INTERFACE = 'INTERFACE';
    UNION = 'UNION';
    ENUM = 'ENUM';
    ENUM_VALUE = 'ENUM_VALUE';
    INPUT_OBJECT = 'INPUT_OBJECT';
    INPUT_FIELD_DEFINITION = 'INPUT_FIELD_DEFINITION';
}
